### ISSUE TITLE
cannot do the long iready lessons with the characters in them

### ISSUE THREAD

**Issue by ken0115** [DevTech-Services/DevHaxx#10]
![Screenshot 2024-01-16 121402](https://github.com/DevTech-Services/DevHaxx/assets/156834675/a6fc1bbe-6588-4266-b04a-7c2c84616fa4)
the hack doesent skip these lessons and they are very long to complete

**Comment by justDarian** [comment]
no idea what those lesson types are 💀

**Comment by ken0115** [comment]
> no idea what those lesson types are 💀

i shared a screenshot?
