### ISSUE TITLE
pls help

### ISSUE THREAD

**Issue by leyner345** [DevTech-Services/DevHaxx#11]
when i try to open the menu to use skip lesson / minutes it is not poping up btw i am on mac
<img width="1440" alt="Screenshot 2024-01-20 at 12 35 05 PM" src="https://github.com/DevTech-Services/DevHaxx/assets/157236211/14c7f104-903d-42d8-af3c-0691a6a1a395">

**Comment by justDarian** [comment]
enable bookmark bar, make bookmark, edit url and paste code, goto the site and click the bookmark

**Comment by leyner345** [comment]
ty
